config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  
  mount Sidekiq::Web => '/sidekiq'
  
  scope "(:locale)", locale: /en|es/ do
    get 'searches/index'
    get 'searches/random'
    post 'searches/create'
    post "searches/send_fact_email"

    devise_for :users
    root 'searches#index'
    
    # Custom Errors
    %w( 404 403 500 400).each do |code|
      get code, :to => "errors#show", :code => code
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :fact_result_categories, class_name: 'FactResultCategory'
  has_many :fact_results, through: :fact_result_categories

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/fact_result.rb
# frozen_string_literal: true

class FactResult < ApplicationRecord
  paginates_per 10
  belongs_to :search
  has_many :fact_result_categories, class_name: 'FactResultCategory'
  has_many :categories, through: :fact_result_categories

  validates :url, presence: true

  validates :value, presence: true
  validates :search, presence: true
end

app/models/fact_result_category.rb
# frozen_string_literal: true

class FactResultCategory < ApplicationRecord
  belongs_to :fact_result
  belongs_to :category
end

app/models/search.rb
# frozen_string_literal: true

class Search < ApplicationRecord
  belongs_to :user
  has_many :fact_results, class_name: 'FactResult'

  before_create :clean_query

  validates :user, presence: true
  private

  def clean_query
    self.query = query.strip.downcase
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :searches, class_name: 'Search'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :set_locale

  # if user is logged in, return current_user, else return guest_user
  def current_or_guest_user
    if current_user
      if session[:guest_user_id] && session[:guest_user_id] != current_user.id
        logging_in
        # reload guest_user to prevent caching problems before destruction
        guest_user(with_retry = false).try(:reload).try(:destroy)
        session[:guest_user_id] = nil
      end
      current_user
    else
      guest_user
    end
  end

  # find guest_user object associated with the current session,
  # creating one as needed
  def guest_user(with_retry = true)
    # Cache the value the first time it's gotten.
    @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)
  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
    session[:guest_user_id] = nil
    guest_user if with_retry
  end

  private

  # called (once) when the user logs in, insert any code your application needs
  # to hand off from guest_user to current_user.
  def logging_in
    # For example:
    # guest_comments = guest_user.comments.all
    # guest_comments.each do |comment|
    # comment.user_id = current_user.id
    # comment.save!
    # end
  end

  def create_guest_user
    user = User.new(email: "chuck_#{Time.now.to_i}#{rand(100)}@norris.com")
    user.save!(validate: false)
    session[:guest_user_id] = user.id
    user
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/concerns/searcheable.rb
# frozen_string_literal: true

module Searcheable
  extend ActiveSupport::Concern

  private

  def get_categories
    response = Faraday.get("#{url_base}/categories")
    render_error(response) if !response.status.eql?(200)
    JSON.parse(response.body)
  end

  def get_facts(query)
      if random_fact?
        get_random_fact
      elsif categorie_fact?(query)
        get_random_by_categorie(query)
      else
        get_fact_by_query(query)
      end
  end

  def get_random_fact
    response = Faraday.get("#{url_base}/random")
    [JSON.parse(response.body)]
  end

  def get_random_by_categorie(query)
    response = Faraday.get("#{url_base}/random?category=#{query}")
    [JSON.parse(response.body)]
  end

  def get_fact_by_query(query)
    response = Faraday.get("#{url_base}/search?query=#{query}")
    JSON.parse(response.body)['result']
  end

  def random_fact?
    params[:search][:query].blank? || params[:commit].eql?('Random')
  end

  def categorie_fact?(query)
    Category.all.map(&:name).uniq.include?(query.downcase)
  end

  def url_base
    Rails.application.credentials.config[:url][:base]
  end

  def render_error(response)
    render "errors/#{response.status}", status: "#{response.status}", layout: 'application'
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
 
  def show
    render status_code.to_s, :status => status_code
  end
 
protected
 
  def status_code
    params[:code] || 500
  end
 
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  include Searcheable

  def index
    @search = Search.new
    @categories = show_categories
    @fact_results = FactResult.joins(:search)
                              .where(search_id: Search.last)
                              .where(searches: { user: current_or_guest_user })
                              .page params[:page]
  end

  def create
    @search = Search.new(search_params)
    @search.user = current_or_guest_user
    @search.query = 'Random' if @search.query.empty?
    @search.save
    respond_to do |format|
      if get_fact_results(@search)
        format.html { redirect_to searches_index_url, notice: I18n.t('query.create_success') }
      else
        format.html { redirect_to searches_index_url, notice: I18n.t('errors.bad_request.message') }
      end
    end
  end

  def send_fact_email
    SendFactResultFactJob.perform_later(current_or_guest_user.email, params[:email])
    redirect_to searches_index_url, notice: I18n.t('mailer.notify')
  end

  private

  def search_params
    params.require(:search).permit(:query, :user_id)
  end

  def get_fact_results(search)
    facts = get_facts(search.query)
    
    if facts.last.has_key?('url')
      facts.each do |result|
        fact_result = FactResult.create(
          value: result['value'],
          search_id: search.id,
          url: result['url']
        )
        if result['categories'].any?
          result['categories'].each do |category_name|
            fact_result.categories << Category.find_or_create_by(name: category_name)
          end
        end
        fact_result
      end
    else
      false
    end
  end

  def persist_categories
    if Category.none?
      get_categories.each do |category_name|
        Category.find_or_create_by(name: category_name)
      end
    # if the last category was created more than a day ago make request
    elsif Category.last.created_at < DateTime.now - 1.day
      get_categories.each do |category_name|
        Category.find_or_create_by(name: category_name)
      end
    end
  end

  def show_categories
    if get_categories.class.eql?(Array)
      persist_categories
    end
    Category.all.pluck(:name).uniq.sort
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InspiringTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "/shared/nav"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/searches/_categories.html.erb
<p class="lead"><%= t("messages.available_categories") %></p>

<ul class= "list-group list-group-horizontal">
  <% if @categories&.any?  %>
    <% @categories.each do |category_name| %>
        <li class= "list-group-item"><%= category_name.capitalize %></li>
    <% end %>
  <% end %>
</ul>
<br>

app/views/searches/_email_form.erb
<%= form_with(url: searches_send_fact_email_path) do |form| %> 
  <div class="input-group">  
    <%= form.email_field  :email, class: "form-control", placeholder: t('email.email_placeholder') %>
    <%= form.submit t('email.send_email'), class: "btn btn-outline-secondary" %>
  </div>
<% end %>
<br>

app/views/searches/_result.html.erb
<% if fact_results.any? %>
  <% fact_results.each do |result| %>
    <div id="<%= dom_id fact_results.last.search %>" class="card">
      <div class="card-header">
        <strong><%= t('activerecord.attributes.search.query') %>:</strong>  <%= result.search.query.capitalize %>
      </div>
      
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p><%= result.value %></p>
          <footer class="blockquote-footer">
          <% if result.categories.any? %>
            <%= result.categories.map(&:name).map(&:capitalize).join(',') %></footer>
          <% end %>
        </blockquote>
      </div>
    </div>
    <br>
  <% end %>
<% else %>
  <p class="lead"><%= t('messages.without_results') %></p>
<% end %>

app/views/searches/_search.html.erb
<%= form_with(model: @search, url: searches_create_path) do |form| %> 
  <% if @search.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@search.errors.count, "error") %> <%= t('query.create_error') %></h2>

      <ul>
      <% @search.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="input-group">
    <%= form.text_field :query, class: "form-control", placeholder: t('query.message') %>
    <%= form.submit t('activerecord.models.search.one'), class: "btn btn-outline-secondary" %>
    <%= form.submit t('query.random'), class: "btn btn-outline-secondary" %>
  </div>
<% end %>
<br>

app/views/searches/index.html.erb
<div class="container">
  <h1 class="display-4"><%= t('activerecord.models.search.one') %></h1>
  <br>
  <%= render "categories", categories: @categories %>
  
  <%= render "search" %>

  <%= render "result", fact_results: @fact_results %> 

  <%= paginate @fact_results, theme: 'bootstrap-5' %>
  
  <hr>
  <%= render "email_form", fact_results: @fact_results %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'English', url_for(locale: :en), class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Español', url_for(locale: :es), class: "nav-link"%>
      </li>
    </ul>
  </div>
</nav>